theme: jekyll-theme-architect
title: Management License WEB use PHP
description: Control dan management license applikasi berbasi web, sehingga dapat mempermudah kita untuk melakukan update, kunci license maupun menghapus aplikasi